### ISSUE TITLE
Error when passing custom plural label

### ISSUE THREAD

**Issue by lmartins** [johnbillion/extended-taxos#15]
Hi,

When I try to pass a custom label as the 4th parameter of `register_extended_taxonomy` I get the following:

```
Notice: register_extended_taxonomy was called <strong>incorrectly</strong>. Name parameters should be passed as an associative array. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 1.5.) in /srv/www/webipack/htdocs/wp-includes/functions.php on line 3560
```

Thanks.

**Comment by lmartins** [comment]
Never mind, just passed is as an array and it fixed it.
Do you want to me to update the inline docs to clarify this?

**Comment by johnbillion** [comment]
Thanks Luis, this library has been a bit neglected lately so the docs are probably not entirely up to date. If you want to submit a PR with that fix, go ahead!
