### ISSUE TITLE
Walker missing

### ISSUE THREAD

**Issue by ekandreas** [johnbillion/extended-taxos#20]
Hi!
When using the plugin as a package loaded via Composer the class Walker that extended-taxos extends, is missing.

**Comment by johnbillion** [comment]
Thanks for the report. How are you autoloading Extended Taxos?

Related: #18

**Comment by ekandreas** [comment]
In the same way as for cpts, take a look at my issue and PR: https://github.com/johnbillion/extended-cpts/issues/35

**Comment by ekandreas** [comment]
https://github.com/johnbillion/extended-cpts/pull/36

**Comment by ekandreas** [comment]
How can we avoid using Walker when it doesn't exist?

**Comment by vinkla** [comment]
+1 I'm also getting this error thrown? Why?

**Comment by johnbillion** [comment]
Extended Taxonomies has now been merged into [Extended CPTs 4.0.0](https://github.com/johnbillion/extended-cpts), and this issue has been fixed.
