### ISSUE TITLE
Advanced options, initial terms, default term, multiple, editable

### ISSUE THREAD

**Issue by roborourke** [johnbillion/extended-taxos#30]
Something I've implemented before would be the ability to define a taxonomy like post formats, I don't think it'd be hard to port over so I'll give it a go at some point but let's see what you think of the potential implementation, using regular taxonomy args:

```php
register_taxonomy( 'name', 'post', [
   'terms' => [ 'slug' => 'Name', 'slug2' => 'Name 2' ], // Default terms
   'default' => 'slug', // mimics behaviour of 'Uncategorized'
   'multiple' => false, // Prevents selection of more than one term, sets walker to radio
   'editable' => false, // makes the terms uneditable via the admin, code only - if true forces 'terms' to exist & prevents their removal
] );
```

**Comment by johnbillion** [comment]
Yeah I'd be happy to implement this if it worked well.

The existing `exclusive` argument was designed to work like your `multiple` argument but it doesn't enforce anything when the terms are assigned.

The `editable` argument could prevent editing/deleting terms via the newly granular terms capabilities in 4.7+.

**Comment by johnbillion** [comment]
This issue was moved to johnbillion/extended-cpts#71
